### ISSUE TITLE
Price missing on robot 110-000-00004

### ISSUE THREAD

**Issue by cmcknight** [cmcknight/central-supply-catalog#59]
Problem Description:

There is no price on the source (Traveller Wiki) for the Dover-Gabe Courier bot and so the price on the product is currently set to zero.

Action needed:

Need to work up a price for the robot which was apparently built using FF&S.

**Comment by bobbyjim** [comment]
Yeah, I can do that.

**Comment by cmcknight** [comment]
Hi Rob,

Thanks, I appreciate it. I’ve retooled some of the CSS to correct some of the issues that were apparently still lingering from the removal of the Materialize CSS framework. That’s been my whole afternoon, but it’s all fixed now (I think). 😂

Also, I noticed you did not credit yourself for the Ultimate Stasis Berth. Was that intentional?

Best regards,

Chuck

**Comment by bobbyjim** [comment]
Unintentional.

I researched that robot a bit.  It’s the model that caused the Shudusham
Accords.  I don’t see any true design of it, and in fact the details appear
to be quite muddled.  I suspect the author didn’t really know what he was
doing.  I can fix it, first in the Wiki, then in the Catalog, by
redesigning it from the sources and using T5.

**Comment by bobbyjim** [comment]
The wiki first claims it as published, which is true, but the design itself
is fan-based, which is likely.

The sources are Book 8, Robots, which text is reprinted in MT Referee's
Companion.  Portions of the text are also quoted in Clay Bush HOTI (which
we really should publish) and Don McKinney's Timeline.

The source is never expanded from Book 8, so I will quote it.  The OCR was
what it was, so don't worry about the mistakes.

In -143, Dover-Gabe, a Sylean manufacturing and mining concern, was awarded
> a large contract for courier robots. These robots provided an efficient and
> secure means of transporting secret military communicstions from place to
> place.
> A tragic attack against the Sylean Federation, which occurred in -112 in Cora
> sector, hslped shape the Third Irnperium's current attitudes about robots.
> A ter- rorist group rigged one of the Dover-Gabe courier robots to
> self-destruct, and man- aged t o sneak it aboard a 90,000-ton Syleen battleship.
> The Empire's Banner was on a goodwill mission in orbit around the world
> Fornol (Core 1715) when the robot's hydragenloxygen f uel-cell exploded.
> Fornol's premier, t w o ambassadors, and the Sylean vice-mjnister were
> killed, along with a host of ship's officers and crewmen.

**Comment by bobbyjim** [comment]
That is a serious explosion.

I suspect that the fuel cell explosion was the trigger, but there must have
been actual ordnance or something added to blow up "a host of ship's
officers and crewmen".

**Comment by bobbyjim** [comment]
>
> built to quickly transport communications material


What is "communications material"?

Comm antennae, dishes, and so on?  Used in constructing listening posts,
e.g. deep space variety?

**Comment by cmcknight** [comment]
Hi Rob,

No worries, I just want to make sure you get credit for your work. 😁

With regards to the robot, a T5 version would be great. 👍

Best regards,

Chuck

**Comment by cmcknight** [comment]
Interesting question. I can read it as you did or as carrying large qualities of bureaucratic communications in some form of storage media.

**Comment by bobbyjim** [comment]
Whatever it is, it has to be (a) physical and (b) military.

   - The most secure way to move military orders, instructions, etc is
   physical rather than beaming it, so I get that.
   - This thing has to be able to, at around TL 10 or TL 11, kill a lot of
   officers and crew of a 90,000 ton vessel.  That implies that it can carry
   the payload of a nuke missile, probably a Large one.
   - So I'd say it is at least a few tons, and could be up to 50 tons as
   the wiki suggests.
   - Its payload is carried internally.

That's an interesting point.  Instead of lashing it to the outside or
dragging it behind, the payload is carried internally.  That suggests it is
able to protect this equipment from all kinds of atmospheres.  It also
suggests a larger size rather than a smaller one.


   - That "Officers" were killed, to me implies an inspection of
   *something* in a pressurized cargo hold of the 90kt battleship.  For
   example, a prototype for a military comms system designed for battleships.


   - Thus my thought of Advanced Extended Antennae Comms or similar, which
   by T5 I know will displace three or four tons each.  Or more.


   - Therefore, say it is a 50 ton drone small craft, as the wiki suggests.


That places design comfortably and squarely into ACS.  We design a small
craft which has no living space or life support, maximizes its payload
section, and install a Brain capable of flying it securely insystem.

Because it is unmanned, it does not need to be particularly fast past the
100D limit.  It runs on "fuel cells" -- we'll see.  It could run on
PowerCells, perhaps Ambient ones that can trickle charge.

**Comment by bobbyjim** [comment]
Whatever it is, it has to be (a) physical and (b) military.

   - The most secure way to move military orders, instructions, etc is
   physical rather than beaming it, so I get that.
   - This thing has to be able to, at around TL 10 or TL 11, kill a lot of
   officers and crew of a 90,000 ton vessel.  That implies that it can carry
   the payload of a nuke missile, probably a Large one.
   - So I'd say it is at least a few tons, and could be up to 50 tons as
   the wiki suggests.
   - Its payload is carried internally.

That's an interesting point.  Instead of lashing it to the outside or
dragging it behind, the payload is carried internally.  That suggests it is
able to protect this equipment from all kinds of atmospheres.  It also
suggests a larger size rather than a smaller one.


   - That "Officers" were killed, to me implies an inspection of
   *something* in a pressurized cargo hold of the 90kt battleship.  For
   example, a prototype for a military comms system designed for battleships.


   - Thus my thought of Advanced Extended Antennae Comms or similar, which
   by T5 I know will displace three or four tons each.  Or more.


   - Therefore, say it is a 50 ton drone small craft, as the wiki suggests.


That places design comfortably and squarely into ACS.  We design a small
craft which has no living space or life support, maximizes its payload
section, and install a Brain capable of flying it securely insystem.

Because it is unmanned, it does not need to be particularly fast past the
100D limit.  It runs on "fuel cells" -- we'll see.  It could run on
PowerCells, perhaps Ambient ones that can trickle charge.

**Comment by bobbyjim** [comment]
T5 has communications equipment that are like this:

   - Extendable Antenna: 3 tons, MCr 1.5.
   - Big Antenna: 10 tons, MCr 2.0.

So suppose we need a 22 ton cargo hold.  I bet we can fit it into a 30 ton
robotic small craft.

Let's give it Maneuver-1, and no power plant.  We'll handwave in
PowerCells: this thing is a size 7 craft, so it's batteries will displace
something like 3 tons.

The computer ... well can I make it a Model/0 bis?  That's just above a
plain Console, but that's big enough to install a Brain, right?

So we have

   Tons Component                            MCr  Notes
------- ----------------------------------- ----- -----------------------
   (30) Streamlined Hull, lifters, 0 a/l fr  3.7  S, lifters, no airlocks
      2 Maneuver Drive-1 (A)                 4    1G
      1 S-O Brain Model/0bis fib             0.7
     22 Cargo Hold Basic                     -
      3 3x Ambient PowerCells                3.0

About MCr 11.

**Comment by bobbyjim** [comment]
Let's add landing legs.

MCr 12.

**Comment by bobbyjim** [comment]
From what I can tell, Fuel Cells in T5 are about the same size as
PowerCells.  I'll just change the notation.  T5 mentions their duration as
well (ten weeks), and the wiki reference to halving that in non-oxygen
environments is reasonable.

**Comment by bobbyjim** [comment]
Tons Component                            MCr  Notes
------- ----------------------------------- ----- -----------------------
   (30) Streamlined Hull, lifters, 0 a/l fr  3.7  S, lifters, no airlocks
    0.5 Landing legs with Pads               0.5
      2 Maneuver Drive-1 (A)                 4    1G
      1 S-O Brain Model/1                    1.5
     22 Cargo Hold Basic                     -
      3 3x Fuel Cells                        3.0  Ten weeks

MCr 12.7

Now with fuel cells, and upgraded to a Model/1.

**Comment by bobbyjim** [comment]
Ah now for the sensors.  I'm going to throw out the speculative sensor
array from the wiki.

All we need is a way to talk to the bosses, and a way to avoid obstacles.
Comm and Proximeter.  And they don't have to be fabulous.  This is a
workhorse.

   Tons Component                            MCr Notes
------- ----------------------------------- ----- -----------------------
     30 Streamlined Hull, lifters, 0 a/l fr  3.7  S, lifters, no airlocks
    0.5 Landing legs with pads               0.5
      2 Maneuver Drive-1 (A)                 4    1 G
      0 AR Surf Communicator                 2
      0 D Surf Proximeter                    0.6
      1 SO Brain Model/1 std                 1.5
     22 Cargo Hold Basic                     0
      3 3x Fuel Cell Array                   3    10 weeks.

MCr 15.3

**Comment by bobbyjim** [comment]
Now I have to come to grips with the term "Quickly" move materials.  1G
doesn't sound quick.

TL11 maxes out at 5G.

And, it turns out that I get 5G without extra effort, so this is CLOSE
ENOUGH to call DONE.


   Tons Component                   MCr  Notes
------- ------------------------- -----  --------------------
     30 Streamlined Hull, lifters   3.7  no airlocks
    0.5 Landing legs with pads      0.5
      2 Maneuver Drive-5 (A)        4.0  5G
      0 AR Surf Communicator        2.0
      0 D Surf Proximeter           0.6
      1 SO Brain Model/1 std        1.5
     22 Cargo Hold Basic             -
      3 3x Fuel Cell Array          3.0  10 weeks

MCr 15.3

**Comment by cmcknight** [comment]
You continue to amaze me sir. 👏👏👏👏

**Comment by bobbyjim** [comment]
One more thing.  Now let's talk about brains.

At TL 11, we have Semi-Organic brains available.  Presumably we might also
have Electronic Brains, but I'm not sure about that.

So let's call it a Semi-Organic, and let's make it average intelligence
(2D).  Let's only keep INT 8, so that's KCr 80.
Basic factory Education (2) + 1 costs another KCr 20.

Max skill levels available are therefore 11.

Half of INT goes to the primary skill (Pilot-4).  One-quarter each go to
two secondaries (Comms-2, Sensors-2).  One-quarter also goes to a hobby,
which is random for each brain.

Leaving room to grow one level.

The brain cost is trivial compared to the cost of the 30 ton craft it's in,
so it's a gimme.

**Comment by bobbyjim** [comment]
Wiki entry updated.

**Comment by bobbyjim** [comment]
CSC entry updated.  PR coming up.
